version: '3'

services:
  postgres:
    image: postgres:15
    restart: always
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - './pgdata:/var/lib/postgresql/data/pgdata'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6
    restart: always
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - './pgadmin_data:/var/lib/pgadmin'
    links:
      - 'postgres:pgsql-server'
